[tool.black]
line-length = 119
target-version = ["py311"] # adaptez à votre version
include = "\\.pyi?$"
exclude = """
/(\n  \\.env_04\n  | \\.git\n  | __pycache__\n  | build\n  | dist\n)/
"""

[tool.isort]
profile = "black"
line_length = 119
py_version = 311
skip = [
  ".env_04",
  "build",
  "dist",
]